// Generated by codegen.ts. Do not edit by hand.
export const openApiProvenance = {
  schemaSource: 'unrecorded',
  schemaSha256: null,
  comparedToSha256: null,
  classification: 'ambiguous',
  generator: {
    package: '@hey-api/openapi-ts',
    version: '0.88.2',
  },
} as const;
