export const docsRedirects: Readonly<Record<string, string>> = {
  '/docs/getting-started': '/docs/start',
  '/docs/getting-started/introduction': '/docs/start',
  '/docs/getting-started/installation': '/docs/start/install',
  '/docs/getting-started/quickstart': '/docs/start/sell-paid-api',
  '/docs/getting-started/creating-agents-with-agents':
    '/docs/products/agent-creation',
  '/docs/concepts': '/docs/build',
  '/docs/concepts/agents': '/docs/reference/configuration',
  '/docs/concepts/entrypoints': '/docs/build/define-capability',
  '/docs/ai-router': '/docs/products/router',
  '/docs/ai-router/opencode': '/docs/products/router',
  '/docs/ai-router/openclaw': '/docs/products/router',
  '/docs/ai-router/ironclaw': '/docs/products/router',
  '/docs/ai-router/nanoclaw': '/docs/products/router',
  '/docs/autonomous-agents': '/docs/start/coding-agent',
  '/docs/autonomous-agents/building-applications': '/docs/start/coding-agent',
  '/docs/skills': '/docs/start/coding-agent',
  '/docs/packages/api-sdk': '/docs/products/hosted-platform',
  '/docs/packages/facilitator': '/docs/operate/facilitator',
  '/docs/migration-guides/v4-runtime': '/docs/migration-guides/v3-runtime',
  '/docs/examples/calling-paid-endpoints': '/docs/buy/call-paid-service',
  '/docs/examples/payment-policies': '/docs/buy/policies-budgets',
  '/docs/examples/wallet': '/docs/buy/wallet',
};
