// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiAgentsByAgentId, getAgentsByAgentIdEntrypoints, getAgentsByAgentIdWellKnownAgentJson, getApiAgents, getApiAgentsByAgentId, getApiAgentsByAgentIdAnalyticsExportCsv, getApiAgentsByAgentIdAnalyticsExportJson, getApiAgentsByAgentIdAnalyticsSummary, getApiAgentsByAgentIdAnalyticsTransactions, getHealth, type Options, postAgentsByAgentIdEntrypointsByKeyInvoke, postApiAgents, postApiAgentsByAgentIdIdentityRetry, putApiAgentsByAgentId } from '../sdk.gen';
import type { DeleteApiAgentsByAgentIdData, DeleteApiAgentsByAgentIdError, DeleteApiAgentsByAgentIdResponse, GetAgentsByAgentIdEntrypointsData, GetAgentsByAgentIdEntrypointsError, GetAgentsByAgentIdEntrypointsResponse, GetAgentsByAgentIdWellKnownAgentJsonData, GetAgentsByAgentIdWellKnownAgentJsonError, GetAgentsByAgentIdWellKnownAgentJsonResponse, GetApiAgentsByAgentIdAnalyticsExportCsvData, GetApiAgentsByAgentIdAnalyticsExportCsvError, GetApiAgentsByAgentIdAnalyticsExportCsvResponse, GetApiAgentsByAgentIdAnalyticsExportJsonData, GetApiAgentsByAgentIdAnalyticsExportJsonError, GetApiAgentsByAgentIdAnalyticsExportJsonResponse, GetApiAgentsByAgentIdAnalyticsSummaryData, GetApiAgentsByAgentIdAnalyticsSummaryError, GetApiAgentsByAgentIdAnalyticsSummaryResponse, GetApiAgentsByAgentIdAnalyticsTransactionsData, GetApiAgentsByAgentIdAnalyticsTransactionsError, GetApiAgentsByAgentIdAnalyticsTransactionsResponse, GetApiAgentsByAgentIdData, GetApiAgentsByAgentIdError, GetApiAgentsByAgentIdResponse, GetApiAgentsData, GetApiAgentsResponse, GetHealthData, GetHealthResponse, PostAgentsByAgentIdEntrypointsByKeyInvokeData, PostAgentsByAgentIdEntrypointsByKeyInvokeError, PostAgentsByAgentIdEntrypointsByKeyInvokeResponse, PostApiAgentsByAgentIdIdentityRetryData, PostApiAgentsByAgentIdIdentityRetryError, PostApiAgentsByAgentIdIdentityRetryResponse, PostApiAgentsData, PostApiAgentsError, PostApiAgentsResponse, PutApiAgentsByAgentIdData, PutApiAgentsByAgentIdError, PutApiAgentsByAgentIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiAgentsQueryKey = (options?: Options<GetApiAgentsData>) => createQueryKey('getApiAgents', options);

/**
 * List agents
 *
 * List all agents for the current owner with pagination.
 */
export const getApiAgentsOptions = (options?: Options<GetApiAgentsData>) => queryOptions<GetApiAgentsResponse, DefaultError, GetApiAgentsResponse, ReturnType<typeof getApiAgentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAgents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiAgentsInfiniteQueryKey = (options?: Options<GetApiAgentsData>): QueryKey<Options<GetApiAgentsData>> => createQueryKey('getApiAgents', options, true);

/**
 * List agents
 *
 * List all agents for the current owner with pagination.
 */
export const getApiAgentsInfiniteOptions = (options?: Options<GetApiAgentsData>) => infiniteQueryOptions<GetApiAgentsResponse, DefaultError, InfiniteData<GetApiAgentsResponse>, QueryKey<Options<GetApiAgentsData>>, number | null | Pick<QueryKey<Options<GetApiAgentsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiAgentsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiAgents({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsInfiniteQueryKey(options)
});

/**
 * Create agent
 *
 * Create a new agent with the given configuration.
 */
export const postApiAgentsMutation = (options?: Partial<Options<PostApiAgentsData>>): UseMutationOptions<PostApiAgentsResponse, PostApiAgentsError, Options<PostApiAgentsData>> => {
    const mutationOptions: UseMutationOptions<PostApiAgentsResponse, PostApiAgentsError, Options<PostApiAgentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAgents({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete agent
 *
 * Delete an agent by its ID.
 */
export const deleteApiAgentsByAgentIdMutation = (options?: Partial<Options<DeleteApiAgentsByAgentIdData>>): UseMutationOptions<DeleteApiAgentsByAgentIdResponse, DeleteApiAgentsByAgentIdError, Options<DeleteApiAgentsByAgentIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteApiAgentsByAgentIdResponse, DeleteApiAgentsByAgentIdError, Options<DeleteApiAgentsByAgentIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiAgentsByAgentId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiAgentsByAgentIdQueryKey = (options: Options<GetApiAgentsByAgentIdData>) => createQueryKey('getApiAgentsByAgentId', options);

/**
 * Get agent
 *
 * Get an agent by its ID.
 */
export const getApiAgentsByAgentIdOptions = (options: Options<GetApiAgentsByAgentIdData>) => queryOptions<GetApiAgentsByAgentIdResponse, GetApiAgentsByAgentIdError, GetApiAgentsByAgentIdResponse, ReturnType<typeof getApiAgentsByAgentIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAgentsByAgentId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsByAgentIdQueryKey(options)
});

/**
 * Update agent
 *
 * Update an existing agent. Only provided fields will be updated.
 */
export const putApiAgentsByAgentIdMutation = (options?: Partial<Options<PutApiAgentsByAgentIdData>>): UseMutationOptions<PutApiAgentsByAgentIdResponse, PutApiAgentsByAgentIdError, Options<PutApiAgentsByAgentIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiAgentsByAgentIdResponse, PutApiAgentsByAgentIdError, Options<PutApiAgentsByAgentIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiAgentsByAgentId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAgentsByAgentIdWellKnownAgentJsonQueryKey = (options: Options<GetAgentsByAgentIdWellKnownAgentJsonData>) => createQueryKey('getAgentsByAgentIdWellKnownAgentJson', options);

/**
 * Get agent manifest
 *
 * Get the agent manifest/card in A2A-compatible format.
 */
export const getAgentsByAgentIdWellKnownAgentJsonOptions = (options: Options<GetAgentsByAgentIdWellKnownAgentJsonData>) => queryOptions<GetAgentsByAgentIdWellKnownAgentJsonResponse, GetAgentsByAgentIdWellKnownAgentJsonError, GetAgentsByAgentIdWellKnownAgentJsonResponse, ReturnType<typeof getAgentsByAgentIdWellKnownAgentJsonQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgentsByAgentIdWellKnownAgentJson({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentsByAgentIdWellKnownAgentJsonQueryKey(options)
});

export const getAgentsByAgentIdEntrypointsQueryKey = (options: Options<GetAgentsByAgentIdEntrypointsData>) => createQueryKey('getAgentsByAgentIdEntrypoints', options);

/**
 * List entrypoints
 *
 * List all entrypoints for an agent.
 */
export const getAgentsByAgentIdEntrypointsOptions = (options: Options<GetAgentsByAgentIdEntrypointsData>) => queryOptions<GetAgentsByAgentIdEntrypointsResponse, GetAgentsByAgentIdEntrypointsError, GetAgentsByAgentIdEntrypointsResponse, ReturnType<typeof getAgentsByAgentIdEntrypointsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgentsByAgentIdEntrypoints({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentsByAgentIdEntrypointsQueryKey(options)
});

/**
 * Invoke entrypoint
 *
 * Execute an agent entrypoint synchronously and return the result.
 */
export const postAgentsByAgentIdEntrypointsByKeyInvokeMutation = (options?: Partial<Options<PostAgentsByAgentIdEntrypointsByKeyInvokeData>>): UseMutationOptions<PostAgentsByAgentIdEntrypointsByKeyInvokeResponse, PostAgentsByAgentIdEntrypointsByKeyInvokeError, Options<PostAgentsByAgentIdEntrypointsByKeyInvokeData>> => {
    const mutationOptions: UseMutationOptions<PostAgentsByAgentIdEntrypointsByKeyInvokeResponse, PostAgentsByAgentIdEntrypointsByKeyInvokeError, Options<PostAgentsByAgentIdEntrypointsByKeyInvokeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAgentsByAgentIdEntrypointsByKeyInvoke({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiAgentsByAgentIdAnalyticsSummaryQueryKey = (options: Options<GetApiAgentsByAgentIdAnalyticsSummaryData>) => createQueryKey('getApiAgentsByAgentIdAnalyticsSummary', options);

/**
 * Get analytics summary
 *
 * Get payment analytics summary for an agent.
 */
export const getApiAgentsByAgentIdAnalyticsSummaryOptions = (options: Options<GetApiAgentsByAgentIdAnalyticsSummaryData>) => queryOptions<GetApiAgentsByAgentIdAnalyticsSummaryResponse, GetApiAgentsByAgentIdAnalyticsSummaryError, GetApiAgentsByAgentIdAnalyticsSummaryResponse, ReturnType<typeof getApiAgentsByAgentIdAnalyticsSummaryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAgentsByAgentIdAnalyticsSummary({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsByAgentIdAnalyticsSummaryQueryKey(options)
});

export const getApiAgentsByAgentIdAnalyticsTransactionsQueryKey = (options: Options<GetApiAgentsByAgentIdAnalyticsTransactionsData>) => createQueryKey('getApiAgentsByAgentIdAnalyticsTransactions', options);

/**
 * Get analytics transactions
 *
 * Get payment transaction history for an agent.
 */
export const getApiAgentsByAgentIdAnalyticsTransactionsOptions = (options: Options<GetApiAgentsByAgentIdAnalyticsTransactionsData>) => queryOptions<GetApiAgentsByAgentIdAnalyticsTransactionsResponse, GetApiAgentsByAgentIdAnalyticsTransactionsError, GetApiAgentsByAgentIdAnalyticsTransactionsResponse, ReturnType<typeof getApiAgentsByAgentIdAnalyticsTransactionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAgentsByAgentIdAnalyticsTransactions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsByAgentIdAnalyticsTransactionsQueryKey(options)
});

export const getApiAgentsByAgentIdAnalyticsExportCsvQueryKey = (options: Options<GetApiAgentsByAgentIdAnalyticsExportCsvData>) => createQueryKey('getApiAgentsByAgentIdAnalyticsExportCsv', options);

/**
 * Export analytics as CSV
 *
 * Export payment analytics data as CSV.
 */
export const getApiAgentsByAgentIdAnalyticsExportCsvOptions = (options: Options<GetApiAgentsByAgentIdAnalyticsExportCsvData>) => queryOptions<GetApiAgentsByAgentIdAnalyticsExportCsvResponse, GetApiAgentsByAgentIdAnalyticsExportCsvError, GetApiAgentsByAgentIdAnalyticsExportCsvResponse, ReturnType<typeof getApiAgentsByAgentIdAnalyticsExportCsvQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAgentsByAgentIdAnalyticsExportCsv({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsByAgentIdAnalyticsExportCsvQueryKey(options)
});

export const getApiAgentsByAgentIdAnalyticsExportJsonQueryKey = (options: Options<GetApiAgentsByAgentIdAnalyticsExportJsonData>) => createQueryKey('getApiAgentsByAgentIdAnalyticsExportJson', options);

/**
 * Export analytics as JSON
 *
 * Export payment analytics data as JSON.
 */
export const getApiAgentsByAgentIdAnalyticsExportJsonOptions = (options: Options<GetApiAgentsByAgentIdAnalyticsExportJsonData>) => queryOptions<GetApiAgentsByAgentIdAnalyticsExportJsonResponse, GetApiAgentsByAgentIdAnalyticsExportJsonError, GetApiAgentsByAgentIdAnalyticsExportJsonResponse, ReturnType<typeof getApiAgentsByAgentIdAnalyticsExportJsonQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAgentsByAgentIdAnalyticsExportJson({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAgentsByAgentIdAnalyticsExportJsonQueryKey(options)
});

/**
 * Retry identity registration
 *
 * Retry failed ERC-8004 identity registration for an agent.
 */
export const postApiAgentsByAgentIdIdentityRetryMutation = (options?: Partial<Options<PostApiAgentsByAgentIdIdentityRetryData>>): UseMutationOptions<PostApiAgentsByAgentIdIdentityRetryResponse, PostApiAgentsByAgentIdIdentityRetryError, Options<PostApiAgentsByAgentIdIdentityRetryData>> => {
    const mutationOptions: UseMutationOptions<PostApiAgentsByAgentIdIdentityRetryResponse, PostApiAgentsByAgentIdIdentityRetryError, Options<PostApiAgentsByAgentIdIdentityRetryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAgentsByAgentIdIdentityRetry({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Health check
 *
 * Check if the service is running and healthy.
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});
