// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8787' | (string & {});
};

export type SerializedEntrypoint = {
    /**
     * Unique identifier for this entrypoint
     */
    key: string;
    /**
     * Human-readable description
     */
    description?: string;
    /**
     * JSON Schema for input validation (empty = accept any)
     */
    inputSchema?: {
        [key: string]: unknown;
    };
    /**
     * JSON Schema for output validation (empty = accept any)
     */
    outputSchema?: {
        [key: string]: unknown;
    };
    /**
     * Type of handler (builtin, js, url, llm, graph, webhook). Defaults to builtin.
     */
    handlerType?: 'builtin' | 'llm' | 'graph' | 'webhook' | 'js' | 'url';
    /**
     * Configuration for the handler
     */
    handlerConfig: {
        name: string;
        [key: string]: unknown | string;
    } | {
        /**
         * Inline JavaScript to execute
         */
        code: string;
        /**
         * Execution timeout override in milliseconds
         */
        timeoutMs?: number;
        /**
         * Optional network allowlist for fetch
         */
        network?: {
            /**
             * Allow-listed hosts for outbound fetch
             */
            allowedHosts: Array<string>;
            /**
             * Network request timeout in milliseconds
             */
            timeoutMs?: number;
        };
        [key: string]: unknown | string | number | {
            /**
             * Allow-listed hosts for outbound fetch
             */
            allowedHosts: Array<string>;
            /**
             * Network request timeout in milliseconds
             */
            timeoutMs?: number;
        } | undefined;
    } | {
        /**
         * Absolute URL to fetch
         */
        url: string;
        /**
         * HTTP method to use
         */
        method?: 'GET' | 'POST';
        /**
         * Headers to include in the request
         */
        headers?: {
            [key: string]: string;
        };
        /**
         * Optional JSON-serializable body (for POST)
         */
        body?: unknown;
        /**
         * Request timeout in milliseconds
         */
        timeoutMs?: number;
        /**
         * Allow-listed hosts for outbound fetch. Use ["*"] to allow any host (not recommended).
         */
        allowedHosts: Array<string>;
        [key: string]: unknown | string | 'GET' | 'POST' | {
            [key: string]: string;
        } | number | Array<string> | undefined;
    } | {
        [key: string]: unknown;
    };
    /**
     * Price in USD to invoke this entrypoint (e.g., "0.01" = $0.01)
     */
    price?: string;
    /**
     * Payment network override for this entrypoint (defaults to agent paymentsConfig.network)
     */
    network?: string;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * Payment configuration for monetizing entrypoints
 */
export type PaymentsConfig = {
    /**
     * Wallet address to receive payments
     */
    payTo: string;
    /**
     * Payment network (e.g., base-sepolia, base, solana-devnet)
     */
    network: string;
    /**
     * URL of the x402 facilitator service
     */
    facilitatorUrl: string;
};

/**
 * Wallet configuration for agent to make payments
 */
export type WalletsConfig = {
    /**
     * Agent wallet configuration for making payments
     */
    agent?: {
        /**
         * Wallet type
         */
        type: 'local' | 'thirdweb' | 'signer';
        /**
         * Private key for local wallet (required for type: local)
         */
        privateKey?: string;
        /**
         * Thirdweb secret key (for type: thirdweb)
         */
        secretKey?: string;
        /**
         * Thirdweb client ID (for type: thirdweb)
         */
        clientId?: string;
        /**
         * Wallet label (for type: thirdweb)
         */
        walletLabel?: string;
        /**
         * Chain ID (for type: thirdweb)
         */
        chainId?: number;
    };
};

/**
 * Agent-to-agent protocol configuration
 */
export type A2aConfig = {
    /**
     * Whether A2A protocol is enabled for this agent
     */
    enabled?: boolean;
};

export type CreateAgent = {
    /**
     * URL-friendly unique identifier
     */
    slug: string;
    /**
     * Human-readable name
     */
    name: string;
    /**
     * Human-readable description
     */
    description?: string;
    /**
     * At least one entrypoint is required
     */
    entrypoints: Array<SerializedEntrypoint>;
    /**
     * Whether the agent can be invoked
     */
    enabled?: boolean;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    paymentsConfig?: PaymentsConfig;
    walletsConfig?: WalletsConfig;
    a2aConfig?: A2aConfig;
};

export type AgentDefinition = CreateAgent & {
    /**
     * Unique identifier
     */
    id: string;
    /**
     * Owner identifier
     */
    ownerId: string;
    /**
     * Agent version
     */
    version: string;
    createdAt: string;
    updatedAt: string;
};

export type AgentListResponse = {
    agents: Array<AgentDefinition>;
    total: number;
    offset: number;
    limit: number;
};

export type _Error = {
    error: string;
    code?: string;
    details?: {
        [key: string]: unknown;
    };
};

export type UpdateAgent = {
    /**
     * URL-friendly unique identifier
     */
    slug?: string;
    /**
     * Human-readable name
     */
    name?: string;
    /**
     * Human-readable description
     */
    description?: string;
    /**
     * At least one entrypoint is required
     */
    entrypoints?: Array<SerializedEntrypoint>;
    /**
     * Whether the agent can be invoked
     */
    enabled?: boolean;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    paymentsConfig?: PaymentsConfig;
    walletsConfig?: WalletsConfig;
    a2aConfig?: A2aConfig;
};

export type AgentManifest = {
    protocolVersion?: string;
    name: string;
    description?: string;
    /**
     * Canonical URL of the agent
     */
    url?: string;
    supportedInterfaces?: Array<{
        url: string;
        protocolBinding: string;
    }>;
    provider?: {
        organization?: string;
        url?: string;
    };
    version?: string;
    documentationUrl?: string;
    capabilities?: {
        streaming?: boolean;
        pushNotifications?: boolean;
        stateTransitionHistory?: boolean;
        extensions?: Array<{
            [key: string]: unknown;
        }>;
    };
    securitySchemes?: {
        [key: string]: unknown;
    };
    security?: Array<unknown>;
    defaultInputModes?: Array<string>;
    defaultOutputModes?: Array<string>;
    skills?: Array<{
        id: string;
        name?: string;
        description?: string;
        tags?: Array<string>;
        examples?: Array<string>;
        inputModes?: Array<string>;
        outputModes?: Array<string>;
        security?: Array<unknown>;
    }>;
    supportsAuthenticatedExtendedCard?: boolean;
    signatures?: Array<{
        protected: string;
        signature: string;
        header?: {
            [key: string]: unknown;
        };
    }>;
    iconUrl?: string;
    payments?: Array<{
        [key: string]: unknown;
    }>;
    registrations?: Array<{
        [key: string]: unknown;
    }>;
    trustModels?: Array<{
        [key: string]: unknown;
    }>;
    ValidationRequestsURI?: string;
    ValidationResponsesURI?: string;
    FeedbackDataURI?: string;
    /**
     * Entrypoint definitions keyed by skill id
     */
    entrypoints: {
        [key: string]: {
            description?: string;
            streaming: boolean;
            input_schema?: unknown;
            output_schema?: unknown;
            pricing?: {
                invoke?: string;
                stream?: string;
            };
            [key: string]: unknown | string | boolean | {
                invoke?: string;
                stream?: string;
            } | undefined;
        };
    };
    [key: string]: unknown | string | Array<{
        url: string;
        protocolBinding: string;
    }> | {
        organization?: string;
        url?: string;
    } | {
        streaming?: boolean;
        pushNotifications?: boolean;
        stateTransitionHistory?: boolean;
        extensions?: Array<{
            [key: string]: unknown;
        }>;
    } | {
        [key: string]: unknown;
    } | Array<unknown> | Array<string> | Array<string> | Array<{
        id: string;
        name?: string;
        description?: string;
        tags?: Array<string>;
        examples?: Array<string>;
        inputModes?: Array<string>;
        outputModes?: Array<string>;
        security?: Array<unknown>;
    }> | boolean | Array<{
        protected: string;
        signature: string;
        header?: {
            [key: string]: unknown;
        };
    }> | Array<{
        [key: string]: unknown;
    }> | Array<{
        [key: string]: unknown;
    }> | Array<{
        [key: string]: unknown;
    }> | {
        [key: string]: {
            description?: string;
            streaming: boolean;
            input_schema?: unknown;
            output_schema?: unknown;
            pricing?: {
                invoke?: string;
                stream?: string;
            };
            [key: string]: unknown | string | boolean | {
                invoke?: string;
                stream?: string;
            } | undefined;
        };
    } | undefined;
};

export type Usage = {
    total_tokens?: number;
    prompt_tokens?: number;
    completion_tokens?: number;
};

export type InvokeResponse = {
    /**
     * Output from the entrypoint handler
     */
    output?: unknown;
    usage?: Usage;
    /**
     * Session ID used for this invocation
     */
    sessionId: string;
    /**
     * Unique request identifier
     */
    requestId: string;
};

export type InvokeRequest = {
    /**
     * Input payload for the entrypoint
     */
    input?: unknown;
    /**
     * Session ID for conversation continuity
     */
    sessionId?: string;
    /**
     * Additional metadata for the invocation
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type Health = {
    /**
     * Health status: ok, degraded, or down
     */
    status: string;
    version?: string;
    timestamp: string;
};

export type GetApiAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of items to skip
         */
        offset?: number | null;
        /**
         * Maximum number of items to return
         */
        limit?: number;
    };
    url: '/api/agents';
};

export type GetApiAgentsResponses = {
    /**
     * List of agents
     */
    200: AgentListResponse;
};

export type GetApiAgentsResponse = GetApiAgentsResponses[keyof GetApiAgentsResponses];

export type PostApiAgentsData = {
    body: CreateAgent;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type PostApiAgentsErrors = {
    /**
     * Validation error
     */
    400: _Error;
    /**
     * Slug already exists
     */
    409: _Error;
};

export type PostApiAgentsError = PostApiAgentsErrors[keyof PostApiAgentsErrors];

export type PostApiAgentsResponses = {
    /**
     * Agent created successfully
     */
    201: AgentDefinition;
};

export type PostApiAgentsResponse = PostApiAgentsResponses[keyof PostApiAgentsResponses];

export type DeleteApiAgentsByAgentIdData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/agents/{agentId}';
};

export type DeleteApiAgentsByAgentIdErrors = {
    /**
     * Agent not found
     */
    404: _Error;
};

export type DeleteApiAgentsByAgentIdError = DeleteApiAgentsByAgentIdErrors[keyof DeleteApiAgentsByAgentIdErrors];

export type DeleteApiAgentsByAgentIdResponses = {
    /**
     * Agent deleted successfully
     */
    204: void;
};

export type DeleteApiAgentsByAgentIdResponse = DeleteApiAgentsByAgentIdResponses[keyof DeleteApiAgentsByAgentIdResponses];

export type GetApiAgentsByAgentIdData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/agents/{agentId}';
};

export type GetApiAgentsByAgentIdErrors = {
    /**
     * Agent not found
     */
    404: _Error;
};

export type GetApiAgentsByAgentIdError = GetApiAgentsByAgentIdErrors[keyof GetApiAgentsByAgentIdErrors];

export type GetApiAgentsByAgentIdResponses = {
    /**
     * Agent definition
     */
    200: AgentDefinition;
};

export type GetApiAgentsByAgentIdResponse = GetApiAgentsByAgentIdResponses[keyof GetApiAgentsByAgentIdResponses];

export type PutApiAgentsByAgentIdData = {
    body: UpdateAgent;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/agents/{agentId}';
};

export type PutApiAgentsByAgentIdErrors = {
    /**
     * Agent not found
     */
    404: _Error;
    /**
     * Slug already exists
     */
    409: _Error;
};

export type PutApiAgentsByAgentIdError = PutApiAgentsByAgentIdErrors[keyof PutApiAgentsByAgentIdErrors];

export type PutApiAgentsByAgentIdResponses = {
    /**
     * Agent updated successfully
     */
    200: AgentDefinition;
};

export type PutApiAgentsByAgentIdResponse = PutApiAgentsByAgentIdResponses[keyof PutApiAgentsByAgentIdResponses];

export type GetAgentsByAgentIdWellKnownAgentJsonData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/.well-known/agent.json';
};

export type GetAgentsByAgentIdWellKnownAgentJsonErrors = {
    /**
     * Agent not found
     */
    404: _Error;
};

export type GetAgentsByAgentIdWellKnownAgentJsonError = GetAgentsByAgentIdWellKnownAgentJsonErrors[keyof GetAgentsByAgentIdWellKnownAgentJsonErrors];

export type GetAgentsByAgentIdWellKnownAgentJsonResponses = {
    /**
     * Agent manifest
     */
    200: AgentManifest;
};

export type GetAgentsByAgentIdWellKnownAgentJsonResponse = GetAgentsByAgentIdWellKnownAgentJsonResponses[keyof GetAgentsByAgentIdWellKnownAgentJsonResponses];

export type GetAgentsByAgentIdEntrypointsData = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/agents/{agentId}/entrypoints';
};

export type GetAgentsByAgentIdEntrypointsErrors = {
    /**
     * Agent not found
     */
    404: _Error;
};

export type GetAgentsByAgentIdEntrypointsError = GetAgentsByAgentIdEntrypointsErrors[keyof GetAgentsByAgentIdEntrypointsErrors];

export type GetAgentsByAgentIdEntrypointsResponses = {
    /**
     * List of entrypoints
     */
    200: Array<SerializedEntrypoint>;
};

export type GetAgentsByAgentIdEntrypointsResponse = GetAgentsByAgentIdEntrypointsResponses[keyof GetAgentsByAgentIdEntrypointsResponses];

export type PostAgentsByAgentIdEntrypointsByKeyInvokeData = {
    body: InvokeRequest;
    path: {
        agentId: string;
        key: string;
    };
    query?: never;
    url: '/agents/{agentId}/entrypoints/{key}/invoke';
};

export type PostAgentsByAgentIdEntrypointsByKeyInvokeErrors = {
    /**
     * Invalid input
     */
    400: _Error;
    /**
     * Agent or entrypoint not found
     */
    404: _Error;
    /**
     * Internal error during invocation
     */
    500: _Error;
};

export type PostAgentsByAgentIdEntrypointsByKeyInvokeError = PostAgentsByAgentIdEntrypointsByKeyInvokeErrors[keyof PostAgentsByAgentIdEntrypointsByKeyInvokeErrors];

export type PostAgentsByAgentIdEntrypointsByKeyInvokeResponses = {
    /**
     * Invocation successful
     */
    200: InvokeResponse;
};

export type PostAgentsByAgentIdEntrypointsByKeyInvokeResponse = PostAgentsByAgentIdEntrypointsByKeyInvokeResponses[keyof PostAgentsByAgentIdEntrypointsByKeyInvokeResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: Health;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
